#!/usr/bin/env python

import subprocess
import argparse
import webbrowser

def make_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument("user", default=None, nargs="?")
    return parser


def main(user):
    if user is None:
        cmd = ["gh", "api", "user", "--jq", ".html_url"]
        url = subprocess.check_output(cmd)[:-1].decode('utf-8')
    else:
        url = f"https://github.com/{user}"

    print(f"Opening {url}")

    webbrowser.open(url)

if __name__ == "__main__":
    parser = make_parser()
    args = parser.parse_args()
    main(args.user)
